### ISSUE TITLE
Music Changes Suggestions

### ISSUE THREAD

**Issue by MrMiguel211** [MetroidAdvRandomizerSystem/MARS-Fusion#10]
- Docking Bays area (including the hallway with speed and pb blocks with the pickup, and reactor) = Default Main Deck
- Past Docking Bays = "Facing a huge reaction"
- Auxiliary Energy room before activation = "Enviromental Ambiance"
  -  Post activation = Operations Deck music
- Operations Deck, Restricted Lab = Operations Deck Music
- Lower Sector 1/Ridley Area = Crisis music

Sectors and boss arena rooms untouched 

and alternatively if possible, but not very important:

- Go mode = Final Mission music
  - It would change when you enter operations deck before fighting SA-X

**Comment by AntyMew** [comment]
Closing with 5f67c09
