### ISSUE TITLE
s2 central shaft zoro looking wrong way

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#107]
![grafik](https://github.com/user-attachments/assets/1495ec4d-f72c-48b0-b2c2-f1382ad9ffcb)

**Comment by cluekitty** [comment]
Did some testing on this. I'm pretty sure this is because the clipdata block just below it is a "stop enemy block" When editing in mage it seems to get fixed. Possibly just need to move that one piece of clipdata down one tile.

**Comment by Miepee** [comment]
If you move the clipdata down one tile, is zazabi dangerous again? (E.g. can you freeze the zoro and jump onto it)

**Comment by cluekitty** [comment]
The clipdata when moved looks to make it stick to the wall again, otherwise it's sticking to the "stop enemy" block underneath it. Moving the clipdata shouldn't affect the sprite other than allowing the moving one to move one tile farther down before turning around.

**Comment by JeffGainsNGames** [comment]
Doesn't that also fix the issue with the ice climb too? Could have swore the zoro turned one block too high

**Comment by Miepee** [comment]
The ice climb is intentional; its what stops zazabi from being dangrous

**Comment by JeffGainsNGames** [comment]
Yes, I'm saying with the block at it's currenr height I'm pretty sure it was too low iirc

**Comment by Miepee** [comment]
No. with the current height hes just high enough that you cant freeze him and jump on him. which is intentional.

**Comment by JeffGainsNGames** [comment]
How does removing that path make it better??
