### ISSUE TITLE
Make the music changes optional

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [MetroidAdvRandomizerSystem/MARS-Fusion#109]
I want the Sector 1 Tourian-like area to play the usual Sector 1 music

**Comment by Miepee** [comment]
There's *a lot* of music changes? Do you want all if them to be optional (as in "all on" or "all off")? Do you want each individual one to be optional? Do you only want some specific ones to be optional?

**Comment by H-A-M-G-E-R** [comment]
induvidual

**Comment by Miepee** [comment]
Won't be a thing. Not only is that a tremendous amount of effort, it would also result in obvious "wrong" songs being played.
And toggling the change for individual songs is not something that's worth it either.

We tried to have a lot of balancing in changing the music in a way that makes it expected, both for randomizer play and non-linearity play. If a specific song selection sounds off to multiple people (and specifically "sounds off" not "i prefer"), then we may reconsider on how to change that specific song.

**Comment by H-A-M-G-E-R** [comment]
I changed my mind: make the sector 1 tourian area music change optional and make the others mandatory

**Comment by Miepee** [comment]
Good that this rando never changed any music in tourian.
