### ISSUE TITLE
Be able to charge your beam without charge beam

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [MetroidAdvRandomizerSystem/MARS-Fusion#111]
for damaging bosses without charge beam or missiles

**Comment by JeffGainsNGames** [comment]
You will be able to choose to start with charge beam when you customize your preset. 
![image](https://github.com/user-attachments/assets/3a12ed32-02cd-4208-ae81-7c7aab3a70f3)

This does not need to be a setting and will achieve the result of always having a charge beam for bosses.

**Comment by Miepee** [comment]
In addition:
-  you can't kill Bosses with only charge beam anyway, because all of them (besides BOX) have a core-x phase.
- even if you were able to start with a weak-charge, all that would accomplish is that for all intents and purposes you could ignore logic for charge beam. Which is bad.

**Comment by H-A-M-G-E-R** [comment]
No, I mean that unused charged power beam: https://tcrf.net/Metroid_Fusion

**Comment by Miepee** [comment]
You were describing functionality that you wanted. And we answered everything relevant to that functionality.

Using sprites just because they're in the game is not a good reason to go add unnecessary functionality just to use those sprites.
