### ISSUE TITLE
Samus collected nearly every metroid infant except one, which escaped containment and ate the X parasites and shed several metroid husks along the way to the landing site, then shed a giant metroid husk there and became omega

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [MetroidAdvRandomizerSystem/MARS-Fusion#117]
Lore. Add several sprite layers with less enemies and a metroid husk in the path the last metroid escaped, like how in vanilla the same event is set after a metroid escaped the restricted lab (or rather, internally, screw attack is recovered).

**Comment by Miepee** [comment]
not interested nor even remotely worth it.
This is a randomizer. We don't need lore.

**Comment by H-A-M-G-E-R** [comment]
So the best bet to respect lore is to let Samus absorb SA-X's core-X in the operations deck and simply let Samus escape in the ship without fighting the omega.

**Comment by Miepee** [comment]
Again. This is a randomizer. We don't need lore.
I repeat this again: please leave the issue tracker for **issues**, not suggestions.
