### ISSUE TITLE
item-select: certain disabled upgrades may not retained when picking up majors

### ISSUE THREAD

**Issue by cluekitty** [MetroidAdvRandomizerSystem/MARS-Fusion#12]
Disabled items pertaining to category of upgrade they are will not be kept if they are disabled and you pick up a new upgrade.

## Explosive Upgrades
![EmuHawk_20240305183309](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/assets/6744963/3b6de1c0-8fe3-47d2-8ea6-c220134085b4)

## Suit/Misc Upgrades
![EmuHawk_20240305184219](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/assets/6744963/8f663b04-93d7-49b3-b0d5-97fa3f6307a4)

## Beam Upgrades
![EmuHawk_20240305185059](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/assets/6744963/fe2cae2c-1db9-457c-9d46-5e17b8f76195)

**Comment by AntyMew** [comment]
Closing with 7561665
