### ISSUE TITLE
Suggestion: convert tabs to spaces

### ISSUE THREAD

**Issue by biosp4rk** [MetroidAdvRandomizerSystem/MARS-Fusion#13]
Not everyone has their github or their IDE configured to use a tab size of 4, so converting to spaces would make sure the formatting looks nice for everyone.

**Comment by cluekitty** [comment]
It might be worth adding an `.editorconfig`. Many IDEs support it natively, or through a plugin.
https://editorconfig.org

**Comment by AntyMew** [comment]
Unfortunately vscode doesn't have proper editorconfig support. I can't easily mass format the repo

**Comment by AntyMew** [comment]
Reformatted with the only extension I could find that plays nice with asm. Let me know if there's any weird formatting
