### ISSUE TITLE
Softlock protection edits should be optional

### ISSUE THREAD

**Issue by JaggerTSG** [MetroidAdvRandomizerSystem/MARS-Fusion#30]
Rooms such as S2: Ripper Roost and the S6 SA-X chase room have OoB clips that make use of the crumble blocks 1 tile off ground. Some players prefer the risk in favor of tricks.

**Comment by AntyMew** [comment]
Added. Affected rooms are currently S2 ripper roost, S2 crumble city, S4 security bypass, S6 zozoro wine cellar, and S6 big shell 1

I'm open to making crumble city a special case so you can still peek it w/o spacejump, but currently it's affected for the sake of consistency
