### ISSUE TITLE
Ensure collecting all items available results in 100% completion

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#36]

**Comment by AntyMew** [comment]
To be clear, what's the behavior you're requesting? It's already implemented in a simple form in [major-completion.s](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/blob/812d4ce2/src/nonlinear/major-completion.s), which includes duplicates of obtained items, empty items, and logically inaccessible locations in the completion percentage. Are you requesting any of those to be excluded?

**Comment by Miepee** [comment]
The behaviour was that if all pickups in the game are collected, that the game should show 100% item collection.

I just read [the message here](https://discord.com/channels/119665192110915584/844229290572906576/1236609384616820737) and thought mars had the same issue. if it doesnt, feel free to just close this as invalid.
