### ISSUE TITLE
Main Deck,  Docking Bay shaft to Silo entry causes weird door transition

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#42]
![grafik](https://github.com/user-attachments/assets/e9b4108f-2254-4621-ba93-824f8beb1a5b)

**Comment by cluekitty** [comment]
![EmuHawk_20240824121630](https://github.com/user-attachments/assets/bb0efe5f-a630-461f-b31e-35926246582f)

**Comment by AntyMew** [comment]
Definitely a regression from fe90b9a
