### ISSUE TITLE
S2 central shaft, upper door not immediately usable?

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#43]
![grafik](https://github.com/user-attachments/assets/654bf3dd-d87e-44bb-a775-22c78a28c5a4)

Shooting that door results in nothing happening.

**Comment by Miepee** [comment]
![grafik](https://github.com/user-attachments/assets/7ac44c33-a18a-4c25-b2b8-9bdd96f5a1f4)
Apparently no door exists.

**Comment by AntyMew** [comment]
There's two room states for this room, and the other is supposed to be unused. This seems to be a regression with event-based transitions from 81edafd

**Comment by Miepee** [comment]
This is still present on 1e965adcd7d9cc61c63ac0f57304006075bb2c12

With both before and after zazabi both doors are blocked/not preset

**Comment by AntyMew** [comment]
Please clarify, I cannot reproduce

**Comment by Miepee** [comment]
- git log:
> 1e965adcd7d9cc61c63ac0f57304006075bb2c12

- do `make`

- run ./bin/m4rs.gba

- set samus value to 18 in debug menu
- enable every lock in debug menu

- go to s2 
- go this path:
![grafik](https://github.com/user-attachments/assets/3fcc603e-fc3d-4092-a73b-1e497a9fc5a4)


- notice cant use upper doors.

**Comment by Miepee** [comment]
The issue is still present for the hatch to ripper tower
