### ISSUE TITLE
Glitchy animation when interacting with certain tiles

### ISSUE THREAD

**Issue by cluekitty** [MetroidAdvRandomizerSystem/MARS-Fusion#45]
Showcased here: https://youtu.be/hipCz6h0kJ8

Interacting with certain tiles seems to show a single frame of "Taking Damage" where no damage is given during certain parts of animations such as landing, running, or rolling in morph.

Currently unsure if other special tiles are affected. Will continue looking to see if other instances show up like this.

List of tiles I've found that seem to be affected:
* `1B` Water Tile (Found in sector 4)
  * Entering water activates, but exiting water does not. (This does not seem to occur with normal BG0 water)
* `1C` Wet Ground Tile (Found in sector 2 Security Access and in several places in Sector 4)
  * Running and landing activates, but rolling in morph does not
* `1D` Dusty Ground Tile (Found in sector 3)
* `2C` Bubbly Ground (Found underwater in sector 4 in many places)
  * Landing on activates, but running and rolling in morph does not
* `2D` Very Dusty Ground Tile (Found in sector 3

All of these tiles seem to play some sound effect when interacting with them in some way.

**Comment by Miepee** [comment]
Regression from 90dbca3d2065ba09f6ddbcd0bcc811c3d40f5b9a

**Comment by Miepee** [comment]
I'm fairly certain that something is wrong with [EnvironmentalVFX](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/blob/8881ba8dc26b3fcfa7f7cb0caee8e10ddfb3b506/inc/structs.inc#L237)

While in vanilla, that value never changes from its 0 value, something causes it in mars to increase to 1 very briefly whenever dust appears. I'm not sure what exactly, but I do know that when [this instruction](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/blob/8881ba8dc26b3fcfa7f7cb0caee8e10ddfb3b506/src/nonlinear/split-suits.s#L146) is replaced with a simple `mov r1 #0`, that disables all flashing instances, including the ones when interacting with these tiles.

**Comment by cluekitty** [comment]
Looked into the oddities with the palette oddities and things and I don't think that the "timers" at 030012F0 thru 0300130F are actually timers. they appear to control how certain particles are rendered when interacting with the environment. There may be multiple uses for this RAM space (at least in vanilla) so the memory mapped in MARS might need to be moved
A very rough format of what I've found is seems to be like this:
```
030012F0 (len 0x10, 2 count, total size 0x20)

030012F0 u8   Particle Effect at feet (slot 1)
030012F1 u8   Particle effect animation timer 1
030012F2 u8   Particle Effect animation frame
030012F3 u8   Unused?
030012F4 u8   Constant Environment timer? (ticks until reset then something happens (eg, health reset or breathing bubbles underwater))
030012F5 u8   Environment damage sound? (seems to indicate certain sounds during environmental damage)
030012F6 u8   seems to be set to 1 when entering/leaving water for 1 frame
030012F7 u8   Unused?
030012F8 u16  Particle effect X Coordinate
030012FA u16  Particle effect Y Coordinate
030012FC u32  Pointer to something or perhaps some other type of value when not a pointer? Seems sound related
03001300..0300130F Repeat of above but for a second particle
```

**Comment by cluekitty** [comment]
It seems that I'm not entirely correct and that the values used in mars are likely correct for the timers. Debugging at 2am isn't always so eye-opening. It may not be the RAM Value itself that's the issue, but perhaps something reading the value in code elsewhere causing the strange behavior.

I found that, these timer RAM sections are read by these functions:
```0x0800C594..C9E0  (len 0x44C)  DrawSamus
0x08006290..63F8  (len 0x168)  SamusHazardDamage
0x080055D4..5A74  (len 0x4A0)  SamusUpdateEnvironmentEffects
0x0800B478..C134  (len 0xCBC)  SamusUpdateGraphics
0x080812F0..8A964 (len 0x674)  ProjectileUpdate```
