### ISSUE TITLE
Immunity to contact damage causes immunity to electric damage

### ISSUE THREAD

**Issue by SchwartzGandhi** [MetroidAdvRandomizerSystem/MARS-Fusion#49]
This only occurs when speedboosting/shinesparking in electrified water, you will still take damage when you have the shinespark stored.

**Comment by AntyMew** [comment]
This seems to occur because electric damage is treated as *contact* damage rather than environmental damage, therefore any source of contact damage immunity (shinespark, screw attack) will make samus immune to electric damage. Will probably need to remove and replace the contact damage to fix this

**Comment by Miepee** [comment]
Closing as wontfix. This is extremely niche (there are only ~5 electricity rooms) and not worth the effort.
*Maybe* we'll rewrite electric damage at one point as environmental damage later to allow for configurable damage from it, but right now that's not a priority.

**Comment by H-A-M-G-E-R** [comment]
I think it's intentional because screw attack can nullify damage from electricity (e.g. zebesian laser and electrified water).
