### ISSUE TITLE
makefile doesnt automatically create the `obj` directory

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#57]
You need to manually create it.

**Comment by AntyMew** [comment]
It doesn't? What about [this line](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/blob/main/Makefile#L20)?

**Comment by AntyMew** [comment]
Ughhhh I remember, make *ignores* those dependencies for some reason I cannot wrap my head around. I don't know how to fix this

**Comment by Miepee** [comment]
doesn't work.
```shell
# mv ./obj ./obj_
# make
md5sum -c metroid4.md5
metroid4.gba: OK
armips src/main.s
src/main.s(2) fatal error: Could not create file /home/narr/Dokumente/gitRepos/MARS-Fusion/obj/m4rs.gba
src/main.s(69) notice: Applying debug patches...
src/main.s(76) notice: Applying optimization patches...
src/main.s(86) notice: Applying quality of life patches...
src/main.s(116) notice: Applying non-linearity patches...
src/main.s(148) notice: Applying randomizer patches...
Aborting.
```

**Comment by AntyMew** [comment]
I tried debugging it as much as I could, I couldn't come up with a solution or even a reason it's ignoring the directory dependencies. Someone who knows make better than I could probably fix it
