### ISSUE TITLE
Save Stations are disabled during escape

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#67]
They should be activated.

**Comment by biosp4rk** [comment]
Wait, why? The escape timer won't start again if you reload the save. And even if it did, what if you saved with not enough time to escape?

**Comment by Miepee** [comment]
The escape timer is gone.
The reason for that is due to higher settings, where you could be expected to go to beat sa-x/cause explosion first and then somehow have to find your way back to the ship.

**Comment by AntyMew** [comment]
This would allow warp to start to bring you back to the intact hangar bay in default settings. Do we want to disable warp to start during the escape sequence and accept any potential hardlocks that could result?

**Comment by Miepee** [comment]
Good question. I'd probably just bite the bullet for now and disable warp to start for now. Might have a custom message saying "warp to start is disabled during the escape".

**Comment by Miepee** [comment]
On second thought, this isn't actually necessary at all.
There is no possibility where changing the stations course is a requirement for progressing in a seed. So you are always able to put triggering the escape for last, at which point its just a matter of finding a way to the ship.
