### ISSUE TITLE
Incorrect spawn points for the new door in sector 5

### ISSUE THREAD

**Issue by SchwartzGandhi** [MetroidAdvRandomizerSystem/MARS-Fusion#70]
when transitioning between Arctic Containment and Crow's Nest, Samus spawns right on top of the hatch, causing some weird movement behaviour.
![image](https://github.com/user-attachments/assets/a4e34f8a-5312-45c9-8e73-55ff761e3c46)
![image](https://github.com/user-attachments/assets/fd210720-c0db-498b-9265-844aab18097c)

**Comment by Miepee** [comment]
which commit?

**Comment by Miepee** [comment]
for the future, please dont refer to commits as "latest" or other vague statements. provide their hash instead.

Can you try rolling back to 7a7b15d5cd2bd526d7dfb7ffd8236627d3ff65e7 and see if you can still repro the issue?

**Comment by SchwartzGandhi** [comment]
commit https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/commit/7a7b15d5cd2bd526d7dfb7ffd8236627d3ff65e7

still spawn in the hatch
![image](https://github.com/user-attachments/assets/d482ee69-702c-410d-8ee4-bded24238c66)
