### ISSUE TITLE
Right door in Data room (lower) in S5 doesn't seem to be a door

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#72]
This door cant be shot if you have lv3
![image](https://github.com/user-attachments/assets/82b7fbea-d336-4aa7-9cb1-5c4012cf2772)

**Comment by JeffGainsNGames** [comment]
![image](https://github.com/user-attachments/assets/87af0b9e-407f-4734-9c28-cac5415d3077)

**Comment by Miepee** [comment]
Looks like the wrong door got hit once again.
