### ISSUE TITLE
Leaving s2 shooting gallery puts s2 into post-nettori state

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#73]
![image](https://github.com/user-attachments/assets/eb5a0930-330a-4fdf-ae1f-43ab230bb089)
Going through this door causes vines to be gone until you re-enter s2.

**Comment by AntyMew** [comment]
This would be a good time to move all the event-based connections to a new list in asm... there's no vanilla connection that would let this happen

**Comment by Miepee** [comment]
duplicate of #33
