### ISSUE TITLE
Change something in s4 pump control save room to avoid getting oob when coming from the right

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#82]
When coming from this direction, you get stuck in the shoot block and thus any input will bring you oob
![grafik](https://github.com/user-attachments/assets/306b4e90-3dbd-4a09-b8a4-4e1227a1af8d)

**Comment by cluekitty** [comment]
I'm not 100% sure how much of an issue this is. I don't think any inputs you give here will actually send you OOB/upwards. Anything that I've tried has either ejected me to the left (holding left when entering the room, or by pressing right when entering the room holding nothing), or ejected me to the right into the door transition (jumping after entering holding nothing, or pressing left after entering holding nothing).

The simplest solution here is likely just removing that block from the room, or we could adjust the door to spawn you farther away from the wall and skip the block when you enter the room.

**Comment by Miepee** [comment]
Ah so it's "only" inverting controls. Not that bad, but would be nice to have avoided.
I personally would prefer adjusting the right door spawn
