### ISSUE TITLE
Center map when switching map to a sector samus is not currently in with unhidden map patch.

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#85]
map after switching goes somewhere into upper left rather than being centered.

**Comment by AntyMew** [comment]
it is centered though? it's centered specifically for the fully unexplored map

**Comment by Miepee** [comment]
It is not centered:
![grafik](https://github.com/user-attachments/assets/c929c90b-6b51-4e39-b483-4970192080fc)
Should be more like this
![grafik](https://github.com/user-attachments/assets/0ae7b426-92ff-4ed2-b9fd-9f1926c8459f)

**Comment by AntyMew** [comment]
centered *for the fully unexplored map*, I said, i.e. *without* the unhidden map patch

**Comment by Miepee** [comment]
Using 56971cf71e4276cf88d8ad321ea6262f695124a8

**Comment by Miepee** [comment]
> centered for the fully unexplored map, I said, i.e. without the unhidden map patch

My bad, meant to clarify that this is for with the unhidden map patch
