### ISSUE TITLE
Anti softlock: s4 reservoir east, make shot blocks not respawn

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#88]
You can get easily get softlocked if you run out of PBs
![grafik](https://github.com/user-attachments/assets/2f8500dc-bf6b-4478-96c0-aa1d7e1567f1)

**Comment by cluekitty** [comment]
@Miepee Just the upper bomb block respawns. Should that also be never-reform?

**Comment by Miepee** [comment]
yes

**Comment by cluekitty** [comment]
PR has been updated to include the bomb block #95
