### ISSUE TITLE
Make reservoir east bomb blocks never respawn

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#93]
![grafik](https://github.com/user-attachments/assets/3edef569-a2ad-4fd2-adb7-1112fca099b5)

This is to help with the generator having issues and making it easier on low trick settings to leave
(Also nice QoL ig)

**Comment by cluekitty** [comment]
These blocks are bomb chain blocks, which I do not believe have a no-respawn variant. New clipdata would need to be coded, or the blocks would need to be replaced with non-chain variants which can only be broken one at a time

**Comment by cluekitty** [comment]
@Miepee If we change these to normal bomb blocks that don't respawn, this would change requirements for logic. Screw attack and also speed booster would be able to break the blocks. Is that an acceptable change?

**Comment by Miepee** [comment]
I'm unsure on that one. It seems like this is a little less of an issue now. Gonna try a few more tweaks soon:tm: and see if this becomes irrelevant by then.

**Comment by Miepee** [comment]
lets close this for now. if it does become a bigger issue we can reopen.
